# Generated by Django 2.1 on 2021-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stream',
            field=models.CharField(default='Science', max_length=255),
        ),
    ]
