# Generated by Django 2.1 on 2021-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20210501_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
